name: tilt_sender
description: Tilt Steering Controller
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^4.0.2
  shared_preferences: ^2.2.2
  flutter_vibrate: ^1.3.0
  udp: ^5.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#080808"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/icon.png
    - assets/icon.svg
